# This is a basic workflow to help you get started with Actions

name: PSGallery Publish

# Controls when the action will run.
on: # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #Cache Modules that are required by publishing modules
      - name: Set required Powershell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v1
        with:
          modules-to-cache: ImportExcel, PSNmap

      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v2
        with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ steps.psmodulecache.outputs.keygen }}

      #Run pwsh functions to publish the module
      - name: Install Required Modules and Publish updated Modules
        if: steps.cacher.outputs.cache-hit != 'true'
        env:
          NUGET_KEY: ${{ secrets.PS_GALLERY_KEY }}
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ${{ steps.psmodulecache.outputs.needed }} -ErrorAction Stop

          function Invoke-PublishModules {
            $ErrorActionPreference = 'Stop'

            $workingdirectory = (get-location).path
            Import-Module "$workingdirectory/Required/PSEventViewer" -force -SkipEditionCheck

            #ActiveDirectory
            $ActiveDirectoryPSGallery = (Find-Module "AdminToolbox.ActiveDirectory" -Repository PSGallery).version
            $ActiveDirectoryGithub = Get-Content "$workingdirectory/AdminToolbox.ActiveDirectory/ChangeLog.md" | Select-Object -Last 1
              if ($ActiveDirectoryGithub -gt $ActiveDirectoryPSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.ActiveDirectory" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #EndpointManagement
            $EndpointManagementPSGallery = (Find-Module "AdminToolbox.EndpointManagement" -Repository PSGallery).version
            $EndpointManagementGithub = Get-Content "$workingdirectory/AdminToolbox.EndpointManagement/ChangeLog.md" | Select-Object -Last 1
              if ($EndpointManagementGithub -gt $EndpointManagementPSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.EndpointManagement" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #Exchange
            $ExchangePSGallery = (Find-Module "AdminToolbox.Exchange" -Repository PSGallery).version
            $ExchangeGithub = Get-Content "$workingdirectory/AdminToolbox.Exchange/ChangeLog.md" | Select-Object -Last 1
              if ($ExchangeGithub -gt $ExchangePSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.Exchange" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #FFTools
            $FFToolsPSGallery = (Find-Module "AdminToolbox.FFTools" -Repository PSGallery).version
            $FFToolsGithub = Get-Content "$workingdirectory/AdminToolbox.FFTools/ChangeLog.md" | Select-Object -Last 1
              if ($FFToolsGithub -gt $FFToolsPSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.FFTools" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #FileManagement
            $FileManagementPSGallery = (Find-Module "AdminToolbox.FileManagement" -Repository PSGallery).version
            $FileManagementGithub = Get-Content "$workingdirectory/AdminToolbox.FileManagement/ChangeLog.md" | Select-Object -Last 1
              if ($FileManagementGithub -gt $FileManagementPSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.FileManagement" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #Fun
            $FunPSGallery = (Find-Module "AdminToolbox.Fun" -Repository PSGallery).version
            $FunGithub = Get-Content "$workingdirectory/AdminToolbox.Fun/ChangeLog.md" | Select-Object -Last 1
              if ($FunGithub -gt $FunPSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.Fun" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #Networking
            $NetworkingPSGallery = (Find-Module "AdminToolbox.Networking" -Repository PSGallery).version
            $NetworkingGithub = Get-Content "$workingdirectory/AdminToolbox.Networking/ChangeLog.md" | Select-Object -Last 1
              if ($NetworkingGithub -gt $NetworkingPSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.Networking" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #Office365
            $Office365PSGallery = (Find-Module "AdminToolbox.Office365" -Repository PSGallery).version
            $Office365Github = Get-Content "$workingdirectory/AdminToolbox.Office365/ChangeLog.md" | Select-Object -Last 1
              if ($Office365Github -gt $Office365PSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.Office365" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #Remoting
            $RemotingPSGallery = (Find-Module "AdminToolbox.Remoting" -Repository PSGallery).version
            $RemotingGithub = Get-Content "$workingdirectory/AdminToolbox.Remoting/ChangeLog.md" | Select-Object -Last 1
              if ($RemotingGithub -gt $RemotingPSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.Remoting" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #VMWareAutomate
            $VMWareAutomatePSGallery = (Find-Module "AdminToolbox.VMWareAutomate" -Repository PSGallery).version
            $VMWareAutomateGithub = Get-Content "$workingdirectory/AdminToolbox.VMWareAutomate/ChangeLog.md" | Select-Object -Last 1
              if ($VMWareAutomateGithub -gt $VMWareAutomatePSGallery ) {
                Publish-Module -Path "$workingdirectory/AdminToolbox.VMWareAutomate" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            #AdminToolbox
            $AdminToolboxPSGallery = (Find-Module AdminToolbox -Repository PSGallery).version
            $AdminToolboxGithub = Get-Content "$workingdirectory/AdminToolbox/ChangeLog.md" | Select-Object -Last 1
              if ($AdminToolboxGithub -gt $AdminToolboxPSGallery ) {
                Install-Module AdminToolbox.ActiveDirectory; Import-Module AdminToolbox.ActiveDirectory
                Install-Module AdminToolbox.EndpointManagement; Import-Module AdminToolbox.EndpointManagement
                Install-Module AdminToolbox.Exchange; Import-Module AdminToolbox.Exchange
                Install-Module AdminToolbox.FFTools; Import-Module AdminToolbox.FFTools
                Install-Module AdminToolbox.FileManagement; Import-Module AdminToolbox.FileManagement
                Install-Module AdminToolbox.Fun; Import-Module AdminToolbox.Fun
                Install-Module AdminToolbox.Networking; Import-Module AdminToolbox.Networking
                Install-Module AdminToolbox.Office365; Import-Module AdminToolbox.Office365
                Install-Module AdminToolbox.Remoting; Import-Module AdminToolbox.Remoting
                Install-Module AdminToolbox.VMWareAutomate; Import-Module AdminToolbox.VMWareAutomate
                Publish-Module -Path "$workingdirectory/AdminToolbox" -NuGetApiKey $env:NUGET_KEY -Verbose
              }

            $ErrorActionPreference = 'continue'

          }
          Invoke-PublishModules




      #THIS IS FOR WORKFLOW TESTING. IT USES THE PTEST MODULE AT /PTEST/PTEST.PSD1
      #- uses: actions/check     out@v2
      #- name: Publish updated Modules
        #env:
          #NUGET_KEY: ${{ secrets.PS_GALLERY_KEY }}
        #shell: pwsh
        #run: |
          #$workingdirectory = (get-location).path
          #function Invoke-PublishModules {
            #$ptestversionPSGallery = (Find-Module ptest -Repository PSGallery).version
            #$ptestversionGithub = Get-Content "$workingdirectory/PTest/Changelog.md" | Select-Object -Last 1
              #if ($ptestversionGithub -gt $ptestversionPSGallery ) {
                #Publish-Module -Path $workingdirectory/PTest -NuGetApiKey $env:NUGET_KEY -Verbose
              #}
          #}
          #Invoke-PublishModules